apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-dogsitter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-dogsitter
  template:
    metadata:
      labels:
        app: api-dogsitter
    spec:
      containers:
        - name: api-dogsitter
          image: 533267353226.dkr.ecr.us-east-2.amazonaws.com/api-dogsitter:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: Grafana__InstanceId
              valueFrom:
                secretKeyRef:
                  name: grafana-credentials
                  key: GRAFANA_INSTANCE_ID
            - name: Grafana__ApiToken
              valueFrom:
                secretKeyRef:
                  name: grafana-credentials
                  key: GRAFANA_API_TOKEN
