// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UDEM.DEVOPS.DogSitter.Infrastructure.DataSource;

#nullable disable

namespace UDEM.DEVOPS.DogSitter.Infrastructure.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260603171623_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UDEM.DEVOPS.DogSitter.Domain.Entities.Cuidador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("activo")
                        .HasColumnType("bit");

                    b.Property<string>("direccion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("fechaInicioExperiencia")
                        .HasColumnType("datetime2");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("email")
                        .IsUnique();

                    b.ToTable("Cuidadores");
                });

            modelBuilder.Entity("UDEM.DEVOPS.DogSitter.Domain.Entities.Perro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("alergias")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<Guid>("cuidadorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("edad")
                        .HasColumnType("smallint");

                    b.Property<string>("horarioComida")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("peso")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid>("razaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("tipoComida")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("cuidadorId");

                    b.HasIndex("razaId");

                    b.ToTable("Perros");
                });

            modelBuilder.Entity("UDEM.DEVOPS.DogSitter.Domain.Entities.Raza", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("corpulencia")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("nivelEnergia")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("observacionesGenerales")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.ToTable("Razas");
                });

            modelBuilder.Entity("UDEM.DEVOPS.DogSitter.Domain.Entities.Perro", b =>
                {
                    b.HasOne("UDEM.DEVOPS.DogSitter.Domain.Entities.Cuidador", "cuidador")
                        .WithMany("perros")
                        .HasForeignKey("cuidadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UDEM.DEVOPS.DogSitter.Domain.Entities.Raza", "raza")
                        .WithMany("perros")
                        .HasForeignKey("razaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("cuidador");

                    b.Navigation("raza");
                });

            modelBuilder.Entity("UDEM.DEVOPS.DogSitter.Domain.Entities.Cuidador", b =>
                {
                    b.Navigation("perros");
                });

            modelBuilder.Entity("UDEM.DEVOPS.DogSitter.Domain.Entities.Raza", b =>
                {
                    b.Navigation("perros");
                });
#pragma warning restore 612, 618
        }
    }
}
