// <auto-generated />
using System;
using DGW.DogSitter.DogWalker.Infrastructure.DataSource;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DGW.DogSitter.DogWalker.Infrastructure.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260222202748_reomvingVoter")]
    partial class reomvingVoter
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DGW.DogSitter.DogWalker.Domain.Entities.Cuidador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("direccion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("fechaInicioExperiencia")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("email")
                        .IsUnique();

                    b.ToTable("Cuidadores");
                });

            modelBuilder.Entity("DGW.DogSitter.DogWalker.Domain.Entities.Perro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("alergias")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<Guid>("cuidadorId")
                        .HasColumnType("uuid");

                    b.Property<short>("edad")
                        .HasColumnType("smallint");

                    b.Property<string>("horarioComida")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("observaciones")
                        .HasColumnType("text");

                    b.Property<decimal>("peso")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<Guid>("razaId")
                        .HasColumnType("uuid");

                    b.Property<string>("tipoComida")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("cuidadorId");

                    b.HasIndex("razaId");

                    b.ToTable("Perros");
                });

            modelBuilder.Entity("DGW.DogSitter.DogWalker.Domain.Entities.Raza", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("corpulencia")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("nivelEnergia")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("observacionesGenerales")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.ToTable("Razas");
                });

            modelBuilder.Entity("DGW.DogSitter.DogWalker.Domain.Entities.Perro", b =>
                {
                    b.HasOne("DGW.DogSitter.DogWalker.Domain.Entities.Cuidador", "cuidador")
                        .WithMany("perros")
                        .HasForeignKey("cuidadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DGW.DogSitter.DogWalker.Domain.Entities.Raza", "raza")
                        .WithMany("perros")
                        .HasForeignKey("razaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("cuidador");

                    b.Navigation("raza");
                });

            modelBuilder.Entity("DGW.DogSitter.DogWalker.Domain.Entities.Cuidador", b =>
                {
                    b.Navigation("perros");
                });

            modelBuilder.Entity("DGW.DogSitter.DogWalker.Domain.Entities.Raza", b =>
                {
                    b.Navigation("perros");
                });
#pragma warning restore 612, 618
        }
    }
}
